name: Test and Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install deps
        run: npm ci
      #- name: Test
      #  run: make test
      #- name: Build
      #  run: make build
      - name: ls
        run: |
          ls -al /home/runner/work/uploader/uploader/
      - name: cat
        run: |
          cat /home/runner/work/uploader/uploader/package.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            - /home/runner/work/uploader/uploader/package.json
